version: '3.8'
services: 
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    networks:
      - back

networks:
  back:
    driver: bridge